# -------------------------------------------------
#  config.yaml   —   unified & UTF-8-clean
# -------------------------------------------------
backtest:
  initial_cash: 100000
  timezone: "America/New_York"
  data_dir: 'data/historical'
  feather_dir: 'data/feather'
  tick_size_market_profile: 0.01
  tick_size_volume_profile: 0.01
  atr_period: 14
  slippage_model: 'percentage'   # 'percentage' | 'none'
  slippage_pct: 0.0005           # 0 .05 %
  # symbol_file: 'strategies/sp_500.txt'


# ------------------ strategies -------------------
strategy:
  name: 'ValueAreaFadeStrategy'   # active strategy
  parameters:

    # -- Volume-Accumulation (unchanged) ----------
    VolumeAccumulationStrategy:
      log_file: 'logs/volume_accumulation_v3.log'
      risk_per_trade_pct: 0.01
      min_price: 3.00
      max_price: 400.00
      consolidation_days: 10
      consolidation_range_pct: 0.15
      poc_midpoint_tolerance_pct: 0.25
      retest_confirmation_bars: 1
      value_area_pct: 0.70
      stop_loss_poc_buffer_pct: 0.02
      min_stop_loss_ticks: 6
      liquidity_cap_pct: 0.02
      profit_target_r: 1.75
      breakeven_trigger_r: 0.75
      entry_time_window:
        start: '10:00:00'
        end:   '14:00:00'
      enable_relative_volume_check: false
      relative_volume_lookback: 20
      relative_volume_ratio: 2
      enable_open_drive: false
      open_drive_r_target: 3
      vwap_stop_pct: 0.01

    # -- Value-Area Fade  -----------
    ValueAreaFadeStrategy:
      log_file: 'logs/value_area_fade.log'

      # -------- profile settings
      profile_type: 'volume'          # 'volume' | 'market'

      # -------- watch-list
      use_symbol_file: true
      symbol_file: 'strategies/sp_500.txt'   # one ticker per line

      # -------- session timing
      session_open_time: '09:30:00'   # used for gap-size check
      entry_time_window:
        start: '10:00:00'
        end:   '15:00:00'
      exit_time: '15:55:00'
      cooldown:
        minutes: 30

      # -------- calculations & filters
      lookback_days: 14
      poc_lookback_days: 5
      poc_dispersion_threshold: 0.015  # max std-dev of POC over lookback period
      value_area_pct: 0.70
      confirmation_window_minutes: 0
      primary_target: 'poc'            # 'poc' | 'vah' (replaces use_poc_target)
      min_dip_ticks: 0
      min_reward_risk_ratio: 1  # min R/R ratio to enter trade
      use_vwap_filter: false
      relative_volume_filter:
        enable: false
        ratio_threshold: 2.0  # Volume must be 2x the time-of-day average

      # --- NEW volatility / structure controls
      min_atr_pct: 0.00           # min ATR as % of price to consider trade
      atr_stop_mult: 1.0              # stop = entry - 0.5 * ATR
      gap_skip_threshold: 0         # skip day if open gap >= 1 ATR
      allowed_shapes: ['D', 'B', 'P', 'L']           # options: ['D', 'B', 'P', 'L', 'T']

      # --- Trigger & Gate (v4.1.0) ----
      trigger_config:
        mode: 'val_only'               # 'val_only' | 'vwap_only' | 'weighted_average'
        vwap_sigma_level: 2.0
        weight_val: 0.3                # only used when mode = weighted_average
        weight_vwap: 0.7               # (must sum to 1.0 with weight_val)
      vwap_stdev_gate:
        enable: false                   # apply independent VWAP-stdev gate
        sigma_level: 2.0

      # -------- risk / sizing
      risk_per_trade_pct: 0.01
      liquidity_cap_pct: 0.05


    # -- everything below is EXACTLY as before ----
    ConsolidationScreenerStrategy:
      log_file: 'logs/consolidation_screener.log'
      min_price: 2.00
      max_price: 100.00
      consolidation_days: 10
      consolidation_range_pct: 0.07
      breakout_volume_ratio: 1.5

    OpenRejectionReverseStrategy:
      profile_type: 'volume'
      log_file: 'logs/open_rejection_reverse.log'
      risk_per_trade_pct: 0.01
      max_allocation_pct: 0.25
      take_profit_r: 2.5
      trailing_stop_r: 1.0
      min_daily_volume: 500000
      min_prev_day_range_pct: 0.03
      timezone: 'America/New_York'

    OpenDriveMomentumStrategy:
      log_file: 'logs/open_drive_momentum.log'
      risk_per_trade_pct: 0.01
      max_allocation_pct: 0.25
      min_risk_per_share: 0.05
      entry_time: '10:00:00'
      exit_time:  '15:55:00'
      timezone: 'America/New_York'

    SimpleMomentumStrategy:
      daily_change_threshold: 0.10
      position_size_pct: 0.01
      r_unit_pct: 0.02

    ValueMigrationStrategy:
      log_file: 'logs/value_migration.log'
      risk_per_trade_pct: 0.02
      max_allocation_pct: 0.25
      timezone: 'America/New_York'
      min_price: 2.0
      max_price: 30.0
      max_daily_trades: 10

    SimplePocCrossStrategy:
      trade_quantity: 100
      lookback_period: 15
      hold_period: 20

    MeanReversionVolumeStrategy:
      log_file: 'logs/mean_reversion_volume.log'
      sma_period: 20
      atr_period: 14
      deviation_multiplier: 1.5
      volume_sma_period: 50
      risk_per_trade_pct: 0.01
      max_allocation_pct: 0.20
      stop_loss_pct: 0.015
      entry_time: '09:45:00'
      exit_time:  '15:50:00'
      timezone: 'America/New_York'

# ------------------ fee model --------------------
fees:
  model: 'tiered'                 # 'zero' | 'fixed' | 'tiered'
  tiered:
    min_trade_fee: 0.35
    fee_per_share: 0.0035
    max_fee_pct_of_trade: 0.01
  fixed:
    trade_fee: 1.00
