# Main configuration for the backtesting engine

backtest:
  initial_cash: 5000.0
  data_dir: 'data/historical'

strategy:
  # The name of the strategy class to run
  name: 'ValueMigrationStrategy'

  # Strategy-specific parameters
  parameters:
    # Risk 1% of total equity on each trade
    risk_per_trade_pct: 0.01