# Main configuration for the backtesting engine

backtest:
  initial_cash: 3000.0
  # The data_path is now the DIRECTORY containing all ticker CSV files.
  data_dir: 'data/historical'

strategy:
  # The name of the strategy class to run
  name: 'OpenDriveMomentumStrategy' # Or any other new strategy
  # Strategy-specific parameters
  parameters:
    trade_quantity: 100 # This will be overridden by risk-based sizing
    risk_per_trade: 0.01