# config.yaml

backtest:
  start_date: '2024-01-22'
  end_date: '2024-01-26'
  initial_cash: 100000
  data_dir: 'data/historical'
  symbols: ['PLTR'] # Focus on a single symbol for debugging

strategy:
  name: 'DebugVisualizationStrategy'
  parameters:
    tick_size: 0.01 # Resolution in dollars
    timezone: 'America/New_York'

fees:
  model: 'zero'