# config.yaml

backtest:
  initial_cash: 3000
  data_dir: 'data/historical'
  tick_size_market_profile: 0.01
  tick_size_volume_profile: 0.01
  min_avg_daily_volume: 200000        # Only scan stocks with avg daily volume > 500k
  # symbol_file: 'strategies/sp_500.txt' # Commented out or leave blank to disable

# --- Select your data source ---
data_source:
  type: 'sqlite' # Options: 'csv' or 'sqlite'
  db_path: 'data/price_data.db' # Path to your SQLite database file

strategy:
  # Set the active strategy here.
  name: 'VolumeAccumulationStrategy' # <--- CHANGE THIS LINE TO USE A NEW STRATEGY

  # --- All strategy parameters are defined below ---
  parameters:

    VolumeAccumulationStrategy:
      log_file: 'logs/volume_accumulation.log'
      min_price: 2.00                 # Minimum price to filter out low-value stocks
      max_price: 100.00             # Maximum price to filter out high-value stocks
      consolidation_days: 10          # Number of days to look back for a consolidation range
      consolidation_range_pct: 0.07   # Max range (as % of low) to be considered consolidation
      breakout_volume_ratio: 1.5      # Volume must be 1.5x the average of the last 10 days
      risk_per_trade_pct: 0.01        # Risk 1% of total equity per trade
      profit_target_r: 1.5            # Profit target is 1.5x the risk
      breakeven_trigger_r: 0.75       # Move SL to breakeven when 75% of PT is reached
      timezone: 'America/New_York'

    ConsolidationScreenerStrategy:
      log_file: 'logs/consolidation_screener.log'
      min_price: 2.00
      max_price: 100.00
      consolidation_days: 10
      consolidation_range_pct: 0.07   # Use your desired value here
      breakout_volume_ratio: 1.5      # Use your desired value here

    OpenRejectionReverseStrategy:
      profile_type: 'volume' # Choose 'volume' or 'market' for the profiler
      log_file: 'logs/open_rejection_reverse.log'
      risk_per_trade_pct: 0.01      # Risk 1% of total equity per trade
      max_allocation_pct: 0.25      # Never allocate more than 25% of equity to a single trade
      take_profit_r: 2.5            # Take profit at 2.5x the initial risk
      trailing_stop_r: 1.0          # Start trailing the stop with the POC once the trade reaches 1R in profit
      min_daily_volume: 500000      # Minimum 500k shares traded on the previous day
      min_prev_day_range_pct: 0.03  # Previous day's range must be at least 3% to be a candidate
      timezone: 'America/New_York'
      # symbols: ['AAPL', 'GOOG']     # uncomment to use specific symbols

    OpenDriveMomentumStrategy:
      log_file: 'logs/open_drive_momentum.log'
      risk_per_trade: 0.01
      max_allocation_pct: 0.25
      min_risk_per_share: 0.05
      entry_time: '10:00:00'
      exit_time: '15:55:00'
      timezone: 'America/New_York'

    SimpleMomentumStrategy:
      daily_change_threshold: 0.10
      position_size_pct: 0.01
      r_unit_pct: 0.02

    ValueMigrationStrategy:
      log_file: 'logs/value_migration.log'
      risk_per_trade_pct: 0.02      # Risk 2% of total equity per trade
      max_allocation_pct: 0.25      # Never allocate more than 25% of equity to a single trade
      timezone: 'America/New_York'
      min_price: 2.0
      max_price: 30.0
      max_daily_trades: 10 # Limit the number of trades per d

    SimplePocCrossStrategy:
      trade_quantity: 100
      lookback_period: 15
      hold_period: 20

    MeanReversionVolumeStrategy: # <--- ADD THIS NEW SECTION
      log_file: 'logs/mean_reversion_volume.log' # You might want to adjust this path
      sma_period: 20
      atr_period: 14
      deviation_multiplier: 1.5
      volume_sma_period: 50
      risk_per_trade_pct: 0.01
      max_allocation_pct: 0.20
      stop_loss_pct: 0.015
      entry_time: '09:45:00' # Adjusted slightly later to ensure data stability
      exit_time: '15:50:00'
      timezone: 'America/New_York'
      # symbols: ['SPY'] # Uncomment to test with a single symbol like SPY if you have data


fees:
  # Available models: 'zero', 'fixed', 'tiered'
  model: 'tiered'

  # Settings for the 'tiered' model
  tiered:
    min_trade_fee: 0.35          # Minimum fee per trade
    fee_per_share: 0.0035          # Cost per share
    max_fee_pct_of_trade: 0.01   # Fee cannot exceed 0.5% of the trade value

  # Settings for the 'fixed' model
  fixed:
    trade_fee: 1.00 # A flat $1 per trade
